"""Add index on reviews.book_id

Revision ID: 584425487448
Revises: ecd1c631cc1f
Create Date: 2025-06-28 19:30:07.671155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584425487448'
down_revision: Union[str, Sequence[str], None] = 'ecd1c631cc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_book_id', 'reviews', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_book_id', table_name='reviews')
    # ### end Alembic commands ###
